"""added otp_code field

Revision ID: 64ac808b8678
Revises: d313120b9fae
Create Date: 2023-12-19 17:33:45.791322

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '64ac808b8678'
down_revision = 'd313120b9fae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_code')
    # ### end Alembic commands ###
