"""changed some relations

Revision ID: 6a27c9ba7631
Revises: 5eb376c94114
Create Date: 2024-01-10 14:13:31.817275

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6a27c9ba7631'
down_revision = '5eb376c94114'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
