"""added photo field

Revision ID: 72d134af429f
Revises: 6a29cc8d481a
Create Date: 2023-12-30 22:09:45.740485

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '72d134af429f'
down_revision = '6a29cc8d481a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('user_group_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_permission_group_id_usergroup', 'permission', type_='foreignkey')
    op.create_foreign_key(op.f('fk_permission_user_group_id_usergroup'), 'permission', 'usergroup', ['user_group_id'], ['id'])
    op.drop_column('permission', 'group_id')
    op.add_column('user', sa.Column('photo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    op.add_column('permission', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_permission_user_group_id_usergroup'), 'permission', type_='foreignkey')
    op.create_foreign_key('fk_permission_group_id_usergroup', 'permission', 'usergroup', ['group_id'], ['id'])
    op.drop_column('permission', 'user_group_id')
    # ### end Alembic commands ###
