"""Added unique checker for usergroup title

Revision ID: 8b4234170e74
Revises: 6a27c9ba7631
Create Date: 2024-01-16 13:40:04.305923

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8b4234170e74'
down_revision = '6a27c9ba7631'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_usergroup_title'), 'usergroup', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_usergroup_title'), 'usergroup', type_='unique')
    # ### end Alembic commands ###
