"""added attempts_count field

Revision ID: a019080fec70
Revises: 895090f5de07
Create Date: 2023-12-20 10:18:57.515220

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a019080fec70'
down_revision = '895090f5de07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('attempts_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'attempts_count')
    # ### end Alembic commands ###
